apiVersion: v1
kind: Pod
metadata:
  name: exist3
  labels:
    name: hello
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - dell
  containers:
  - name: exist1
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "10Mi"
        cpu: "5000m"
