apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs
  nfs:
    path: /nfsdata/mysql-pv
    server: 192.168.18.30
