apiVersion: v1
kind: Pod
metadata:
  name: exist1
  labels:
    name: hello
spec:
  containers:
  - name: exist1
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "10Mi"
        cpu: "5000m"
