apiVersion: v1
kind: Pod
metadata:
  name: exist4
  labels:
    name: hello
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - dave-desktop
  containers:
  - name: exist4
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "10Mi"
        cpu: "5000m"
      limits:
        memory: "64Mi"
