apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dave
  template:
    metadata:
      labels:
        name: dave
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
