apiVersion: v1
kind: Pod
metadata:
  name: exist1
  labels:
    name: hello
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - dave-desktop
  containers:
  - name: exist1
    image: k8s.gcr.io/pause:2.0
