kind: Pod
apiVersion: v1
metadata:
  name: preemptor
  labels:
    name: dave
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/region1
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        name: dave
  - maxSkew: 1
    topologyKey: kubernetes.io/region2
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchExpressions:
      - key: name
        operator: Exists
  priorityClassName: system-cluster-critical  //mask this line will make this pod pending since no preemption will happen.
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
