kind: Pod
apiVersion: v1
metadata:
  name: mypod-1
  labels:
    name: dave
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/region
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        name: dave
  - maxSkew: 1
    topologyKey: kubernetes.io/unexist
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchExpressions:
      - key: name
        operator: Exists
  #priorityClassName: system-cluster-critical
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
