# this is optional, but have this with the annotation "storageclass.kubernetes.io/is-default-class"
# will help to support the sc without the storage class name defined.
# volumeClaimTemplates:storageClassName
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
