apiVersion: v1
kind: Pod
metadata:
  name: pod-ephemeral
spec:
  containers:
    - name: podcsi
      image: busybox
      args:
      - /bin/sh
      - -c
      - sleep 30000
      volumeMounts:
      - mountPath: "/mydata"
        name: mydata
  volumes:
    - name: mydata
      csi:
        driver: hostpath.csi.k8s.io
