apiVersion: v1
kind: Pod
metadata:
  name: podcsi
spec:
  containers:
    - name: podcsi
      image: busybox
      args:
      - /bin/sh
      - -c
      - sleep 30000
      volumeMounts:
      - mountPath: "/mydata"
        name: mydata
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: csi-pvc
