apiVersion: v1
kind: Pod
metadata:
  name: podcsiupdate
spec:
  containers:
    - name: podcsiupdate
      image: busybox
      args:
      - /bin/sh
      - -c
      - sleep 30000
      volumeMounts:
      - mountPath: "/mydata"
        name: mydata
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: hpvc-restore
